/* This file is generated by starship */

#ifndef _ZJV_MAGIC_DEVICE_H
#define _ZJV_MAGIC_DEVICE_H
#define MAGIC_RANDOM 0x00
#define MAGIC_RDM_WORD 0x08
#define MAGIC_RDM_FLOAT 0x010
#define MAGIC_RDM_DOUBLE 0x018
#define MAGIC_RDM_TEXT_ADDR 0x020
#define MAGIC_RDM_DATA_ADDR 0x028
#define MAGIC_MEPC_NEXT 0x030
#define MAGIC_SEPC_NEXT 0x038
#define MAGIC_RDM_PTE 0x040
#define MAX_MAGIC_SPACE 0x048

#endif
